In [10]:
import numpy as np
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.amax(x,axis=0)
y=y/100


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [3]:
def derivative_sigmoid(x):
    return x*(1-x)


In [14]:
epoch=10
lr=0.2
inp=2
hid=3
out=1

In [21]:
wh=np.random.uniform(size=(inp,hid))
print(wh)
bh=np.random.uniform(size=(1,hid))
print(bh)
wout=np.random.uniform(size=(hid,out))
print(wout)
bout=np.random.uniform(size=(1,out))
print(bout)

[[0.63697535 0.1647869  0.90783656]
 [0.56637979 0.97159282 0.59442024]]
[[0.94148514 0.94272679 0.5651041 ]]
[[0.58173918]
 [0.42957402]
 [0.47913914]]
[[0.03646288]]


In [23]:
for i in range(epoch):
    hinp1=np.dot(x,wh)
    print(hinp1)
    hinp=hinp1+bh
   # print(hinp)
    hlayer_act=sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    

[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.08145075 1.19964461]
 [0.52698056 0.59470275 0.63284565]
 [1.01456188 0.81251544 1.30411672]]
[[0.99103003 1.0814

In [33]:
Eo=y-output
outgrad=derivative_sigmoid(out)
d_out=Eo*outgrad
EH=d_out.dot(wout.T)
hiddengrad=derivative_sigmoid(hlayer_act)
d_hiddenlayer=EH*hiddengrad
wout+=hlayer_act.T.dot(d_out)
wh+=x.T.dot(d_hiddenlayer)*lr
print("input\n"+str(x))
print("actual output\n"+str(y))
print("the predicted output\n",output)

input
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output
[[0.92]
 [0.86]
 [0.89]]
the predicted output
 [[0.71120426]
 [0.70548061]
 [0.71120543]]
