In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("find.csv")
data

Sky AirTemp Humidity    Wind Water Forecast  EnjoySport
0  sunny    warm   normal  strong  warm     same           1
1  sunny    warm     high  strong  warm     same           1
2  rainy    cold     high  strong  warm   change           0
3  sunny    warm     high  strong  cool   change           1

In [3]:
df=pd.DataFrame(data)

In [4]:
data[0:2]

Sky AirTemp Humidity    Wind Water Forecast  EnjoySport
0  sunny    warm   normal  strong  warm     same           1
1  sunny    warm     high  strong  warm     same           1

In [5]:
data.loc[0:2,["Wind"]]

Wind
0  strong
1  strong
2  strong

In [6]:
df.loc[:,["Wind"]]

Wind
0  strong
1  strong
2  strong
3  strong

In [7]:
da={"a":np.arange(0,10),"b":np.arange(10,20)}
da

{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'b': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])}

In [8]:
dd=pd.DataFrame(da)
dd

a   b
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
5  5  15
6  6  16
7  7  17
8  8  18
9  9  19

In [11]:
a=np.arange(0,20)
b=np.arange(20,40)
print(a,b)
print(a+b)
print(a-b)
print(a*b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]
[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20
 -20 -20]
[  0  21  44  69  96 125 156 189 224 261 300 341 384 429 476 525 576 629
 684 741]


In [14]:
a[b>15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
import matplotlib.pyplot as plt